import { CoachMarkFlow } from '@/types/coachMark';

export const COACH_MARK_FLOWS: CoachMarkFlow[] = [
  {
    flowName: 'first_house_creation',
    displayName: 'Create Your First House',
    targetScreen: '(tabs)/index',
    priority: 1,
    triggerCondition: 'no_houses_exist',
    steps: [
      {
        stepId: 'create_house_button',
        targetId: 'create_house_button',
        title: 'Create Your First House',
        description: 'Tap here to create a house where you and your friends can track scores and compete!',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'tap',
        autoAdvanceOnAction: true,
      },
    ],
  },
  {
    flowName: 'house_features_tour',
    displayName: 'Discover House Features',
    targetScreen: 'house/[id]',
    priority: 2,
    triggerCondition: 'first_house_created',
    steps: [
      {
        stepId: 'add_game_button',
        targetId: 'add_game_button',
        title: 'Start a Game',
        description: 'Create a new game to start tracking scores with your house members.',
        position: 'bottom',
        highlightType: 'rectangle',
        actionRequired: 'none',
        highlightPadding: 12,
      },
      {
        stepId: 'house_leaderboard',
        targetId: 'house_leaderboard',
        title: 'View Leaderboard',
        description: 'See how you rank against your housemates. The more you play and win, the higher you climb!',
        position: 'top',
        highlightType: 'rectangle',
        actionRequired: 'none',
        highlightPadding: 8,
      },
      {
        stepId: 'house_settings',
        targetId: 'house_settings',
        title: 'Customize Your House',
        description: 'Tap here to change your house name, emoji, colors, and invite new members.',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'game_templates_tour',
    displayName: 'Choose a Game Template',
    targetScreen: 'game-templates',
    priority: 3,
    triggerCondition: 'first_game_creation',
    steps: [
      {
        stepId: 'game_template_card',
        targetId: 'game_template_card_0',
        title: 'Pick a Game Type',
        description: 'Choose from pre-made templates or create a custom game. Each template has unique scoring rules!',
        position: 'bottom',
        highlightType: 'rectangle',
        actionRequired: 'none',
        highlightPadding: 10,
      },
      {
        stepId: 'custom_game_button',
        targetId: 'custom_game_button',
        title: 'Create Custom Game',
        description: 'Want something unique? Create your own game with custom scoring rules.',
        position: 'top',
        highlightType: 'rectangle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'game_session_flow',
    displayName: 'Playing Your First Game',
    targetScreen: 'game-session/[gameId]',
    priority: 4,
    triggerCondition: 'first_game_started',
    steps: [
      {
        stepId: 'score_input',
        targetId: 'score_input_0',
        title: 'Enter Scores',
        description: 'Tap to enter scores for each player. The system will automatically calculate rankings!',
        position: 'top',
        highlightType: 'rectangle',
        actionRequired: 'none',
        highlightPadding: 8,
      },
      {
        stepId: 'complete_game_button',
        targetId: 'complete_game_button',
        title: 'Finish the Game',
        description: 'When all scores are entered, tap here to complete the game and update the leaderboard.',
        position: 'top',
        highlightType: 'rectangle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'social_features_tour',
    displayName: 'Connect with Friends',
    targetScreen: '(tabs)/friends',
    priority: 5,
    triggerCondition: 'no_friends_after_3_days',
    steps: [
      {
        stepId: 'add_friend_button',
        targetId: 'add_friend_button',
        title: 'Add Friends',
        description: 'Search for friends by username to connect and invite them to your houses!',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
      },
      {
        stepId: 'friend_requests_tab',
        targetId: 'friend_requests_tab',
        title: 'Manage Requests',
        description: 'View incoming friend requests here and accept the ones you want to connect with.',
        position: 'bottom',
        highlightType: 'rectangle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'profile_customization',
    displayName: 'Customize Your Profile',
    targetScreen: '(tabs)/profile',
    priority: 6,
    triggerCondition: 'no_avatar_after_1_day',
    steps: [
      {
        stepId: 'avatar_section',
        targetId: 'avatar_section',
        title: 'Add Profile Photo',
        description: 'Tap your avatar to upload a profile photo and personalize your account!',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
        highlightPadding: 10,
      },
      {
        stepId: 'badges_section',
        targetId: 'badges_section',
        title: 'Unlock Badges',
        description: 'Complete achievements to unlock badges and show off your accomplishments!',
        position: 'top',
        highlightType: 'rectangle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'shop_introduction',
    displayName: 'Explore the Shop',
    targetScreen: '(tabs)/shop',
    priority: 7,
    triggerCondition: 'first_shop_visit',
    steps: [
      {
        stepId: 'kit_preview',
        targetId: 'kit_preview_0',
        title: 'Unlock Themes',
        description: 'Earn coins by playing games and use them to unlock beautiful color themes for your houses!',
        position: 'bottom',
        highlightType: 'rectangle',
        actionRequired: 'none',
        highlightPadding: 12,
      },
      {
        stepId: 'coins_display',
        targetId: 'coins_display',
        title: 'Your Coins',
        description: 'This shows your current coin balance. Win games to earn more!',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
      },
    ],
  },
  {
    flowName: 'join_house_tutorial',
    displayName: 'Join a House',
    targetScreen: '(tabs)/index',
    priority: 8,
    triggerCondition: 'no_houses_after_signup',
    steps: [
      {
        stepId: 'join_house_button',
        targetId: 'join_house_button',
        title: 'Join Existing House',
        description: 'Have an invite code? Tap here to join a house your friends already created!',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
      },
      {
        stepId: 'scan_qr_button',
        targetId: 'scan_qr_button',
        title: 'Scan QR Code',
        description: 'You can also join a house by scanning a QR code shared by the house admin.',
        position: 'bottom',
        highlightType: 'circle',
        actionRequired: 'none',
      },
    ],
  },
];
